const nome = prompt("Qual o seu nome?")
const comidaFavorita1 = prompt("Qual a sua 1º comidas favoritas?")
const comidaFavorita2 = prompt("Qual a sua 2º comidas favoritas?")
const comidaFavorita3 = prompt("Qual a sua 3º comidas favoritas?")
console.log(`Estas são as comidas favoritas de ${nome} \n ${comidaFavorita1} \n ${comidaFavorita2} \n ${comidaFavorita3}`) 
